server:
  port: 9080

expense-service:
  locator: expense-service
aggregate-service:
  locator: aggregate-service
gateway:
  locator: gateway
oauth:
  url: ${OAUTH_URL:http://localhost:8090/uaa/oauth/token}

jwt:
  security:
    key: zab23bc8934gh=1
  token:
    validity: 1800000

grant:
  type: password

client:
  secret: secret

spring:
  application:
    name: ui
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://uaa:8090/uaa/oauth/token
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8090/uaa/token_keys}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org:
      apache:
        client: DEBUG
      httpclient:
        wire: DEBUG
      springframework:
        web:
          client:
            RestTemplate: DEBUG
